version: '3.6'
services:
  server:
    build: 
      dockerfile: Dockerfile.local
      context: .
      target: build
    command: air
    volumes:
      - .:/app
    ports:
      - "8088:8088"
    depends_on:
      - postgresql
    environment: 
      - PORT=8088
      - DB_HOST=postgresql
      - DB_USERNAME=postgres
      - DB_PASSWORD=testtesttest
      - USERNAME=blah
      - PASSWORD=blah
    
  postgresql:
    image: postgres
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: testtesttest